version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"  # Измените внешний порт
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=stori_arenda_pro;Port=5432;User Id=postgres;Password=12873465Tam;Command Timeout=120
      - ASPNETCORE_URLS=http://+:5000  # Измените внутренний порт
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stori_arenda_pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12873465Tam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: